name: Terraform GCP Infrastructure Deployment

on:
  push:
    branches:
      - main
      - DEV
    paths:
      - 'terraform-infra/dev/**'
      - 'terraform-modules/**'

  workflow_dispatch:

env:
  TF_VERSION: 1.6.6
  GCP_PROJECT_ID: innova-d365-gcp-project
  REGION: us-central1

jobs:
  terraform:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform-infra/dev

    steps:
      # 1️⃣ Checkout Repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init -upgrade

      # 5️⃣ Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
